exclude:
  - data/issuers/skylark/stores
  - data/issuers/colowide/stores
  - data/issuers/create/stores
  - data/issuers/monogatari/stores
  - cloudflare
  - tools
  - tests
  - docs
  - data/expiry_master.csv
